"""ISO-3166 country and US state tables for the country pre-check.

GENERATED FILE - regenerate with scripts/generate_country_data.py; never
edit by hand. COUNTRIES rows are (canonical name, alpha-2, alpha-3,
continent code) as published by the geonamescache database; US_STATES maps
lowercase state names and uppercase USPS abbreviations to the state name,
as published by the us package.
"""

# fmt: off
COUNTRIES: tuple = (
    ('Andorra', 'AD', 'AND', 'EU'),
    ('United Arab Emirates', 'AE', 'ARE', 'AS'),
    ('Afghanistan', 'AF', 'AFG', 'AS'),
    ('Antigua and Barbuda', 'AG', 'ATG', 'NA'),
    ('Anguilla', 'AI', 'AIA', 'NA'),
    ('Albania', 'AL', 'ALB', 'EU'),
    ('Armenia', 'AM', 'ARM', 'AS'),
    ('Netherlands Antilles', 'AN', 'ANT', 'NA'),
    ('Angola', 'AO', 'AGO', 'AF'),
    ('Antarctica', 'AQ', 'ATA', 'AN'),
    ('Argentina', 'AR', 'ARG', 'SA'),
    ('American Samoa', 'AS', 'ASM', 'OC'),
    ('Austria', 'AT', 'AUT', 'EU'),
    ('Australia', 'AU', 'AUS', 'OC'),
    ('Aruba', 'AW', 'ABW', 'NA'),
    ('Aland Islands', 'AX', 'ALA', 'EU'),
    ('Azerbaijan', 'AZ', 'AZE', 'AS'),
    ('Bosnia and Herzegovina', 'BA', 'BIH', 'EU'),
    ('Barbados', 'BB', 'BRB', 'NA'),
    ('Bangladesh', 'BD', 'BGD', 'AS'),
    ('Belgium', 'BE', 'BEL', 'EU'),
    ('Burkina Faso', 'BF', 'BFA', 'AF'),
    ('Bulgaria', 'BG', 'BGR', 'EU'),
    ('Bahrain', 'BH', 'BHR', 'AS'),
    ('Burundi', 'BI', 'BDI', 'AF'),
    ('Benin', 'BJ', 'BEN', 'AF'),
    ('Saint Barthelemy', 'BL', 'BLM', 'NA'),
    ('Bermuda', 'BM', 'BMU', 'NA'),
    ('Brunei', 'BN', 'BRN', 'AS'),
    ('Bolivia', 'BO', 'BOL', 'SA'),
    ('Bonaire, Saint Eustatius and Saba', 'BQ', 'BES', 'NA'),
    ('Brazil', 'BR', 'BRA', 'SA'),
    ('Bahamas', 'BS', 'BHS', 'NA'),
    ('Bhutan', 'BT', 'BTN', 'AS'),
    ('Bouvet Island', 'BV', 'BVT', 'AN'),
    ('Botswana', 'BW', 'BWA', 'AF'),
    ('Belarus', 'BY', 'BLR', 'EU'),
    ('Belize', 'BZ', 'BLZ', 'NA'),
    ('Canada', 'CA', 'CAN', 'NA'),
    ('Cocos Islands', 'CC', 'CCK', 'AS'),
    ('Democratic Republic of the Congo', 'CD', 'COD', 'AF'),
    ('Central African Republic', 'CF', 'CAF', 'AF'),
    ('Republic of the Congo', 'CG', 'COG', 'AF'),
    ('Switzerland', 'CH', 'CHE', 'EU'),
    ('Ivory Coast', 'CI', 'CIV', 'AF'),
    ('Cook Islands', 'CK', 'COK', 'OC'),
    ('Chile', 'CL', 'CHL', 'SA'),
    ('Cameroon', 'CM', 'CMR', 'AF'),
    ('China', 'CN', 'CHN', 'AS'),
    ('Colombia', 'CO', 'COL', 'SA'),
    ('Costa Rica', 'CR', 'CRI', 'NA'),
    ('Serbia and Montenegro', 'CS', 'SCG', 'EU'),
    ('Cuba', 'CU', 'CUB', 'NA'),
    ('Cabo Verde', 'CV', 'CPV', 'AF'),
    ('Curacao', 'CW', 'CUW', 'NA'),
    ('Christmas Island', 'CX', 'CXR', 'OC'),
    ('Cyprus', 'CY', 'CYP', 'EU'),
    ('Czechia', 'CZ', 'CZE', 'EU'),
    ('Germany', 'DE', 'DEU', 'EU'),
    ('Djibouti', 'DJ', 'DJI', 'AF'),
    ('Denmark', 'DK', 'DNK', 'EU'),
    ('Dominica', 'DM', 'DMA', 'NA'),
    ('Dominican Republic', 'DO', 'DOM', 'NA'),
    ('Algeria', 'DZ', 'DZA', 'AF'),
    ('Ecuador', 'EC', 'ECU', 'SA'),
    ('Estonia', 'EE', 'EST', 'EU'),
    ('Egypt', 'EG', 'EGY', 'AF'),
    ('Western Sahara', 'EH', 'ESH', 'AF'),
    ('Eritrea', 'ER', 'ERI', 'AF'),
    ('Spain', 'ES', 'ESP', 'EU'),
    ('Ethiopia', 'ET', 'ETH', 'AF'),
    ('Finland', 'FI', 'FIN', 'EU'),
    ('Fiji', 'FJ', 'FJI', 'OC'),
    ('Falkland Islands', 'FK', 'FLK', 'SA'),
    ('Micronesia', 'FM', 'FSM', 'OC'),
    ('Faroe Islands', 'FO', 'FRO', 'EU'),
    ('France', 'FR', 'FRA', 'EU'),
    ('Gabon', 'GA', 'GAB', 'AF'),
    ('United Kingdom', 'GB', 'GBR', 'EU'),
    ('Grenada', 'GD', 'GRD', 'NA'),
    ('Georgia', 'GE', 'GEO', 'AS'),
    ('French Guiana', 'GF', 'GUF', 'SA'),
    ('Guernsey', 'GG', 'GGY', 'EU'),
    ('Ghana', 'GH', 'GHA', 'AF'),
    ('Gibraltar', 'GI', 'GIB', 'EU'),
    ('Greenland', 'GL', 'GRL', 'NA'),
    ('Gambia', 'GM', 'GMB', 'AF'),
    ('Guinea', 'GN', 'GIN', 'AF'),
    ('Guadeloupe', 'GP', 'GLP', 'NA'),
    ('Equatorial Guinea', 'GQ', 'GNQ', 'AF'),
    ('Greece', 'GR', 'GRC', 'EU'),
    ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 'AN'),
    ('Guatemala', 'GT', 'GTM', 'NA'),
    ('Guam', 'GU', 'GUM', 'OC'),
    ('Guinea-Bissau', 'GW', 'GNB', 'AF'),
    ('Guyana', 'GY', 'GUY', 'SA'),
    ('Hong Kong', 'HK', 'HKG', 'AS'),
    ('Heard Island and McDonald Islands', 'HM', 'HMD', 'AN'),
    ('Honduras', 'HN', 'HND', 'NA'),
    ('Croatia', 'HR', 'HRV', 'EU'),
    ('Haiti', 'HT', 'HTI', 'NA'),
    ('Hungary', 'HU', 'HUN', 'EU'),
    ('Indonesia', 'ID', 'IDN', 'AS'),
    ('Ireland', 'IE', 'IRL', 'EU'),
    ('Israel', 'IL', 'ISR', 'AS'),
    ('Isle of Man', 'IM', 'IMN', 'EU'),
    ('India', 'IN', 'IND', 'AS'),
    ('British Indian Ocean Territory', 'IO', 'IOT', 'AS'),
    ('Iraq', 'IQ', 'IRQ', 'AS'),
    ('Iran', 'IR', 'IRN', 'AS'),
    ('Iceland', 'IS', 'ISL', 'EU'),
    ('Italy', 'IT', 'ITA', 'EU'),
    ('Jersey', 'JE', 'JEY', 'EU'),
    ('Jamaica', 'JM', 'JAM', 'NA'),
    ('Jordan', 'JO', 'JOR', 'AS'),
    ('Japan', 'JP', 'JPN', 'AS'),
    ('Kenya', 'KE', 'KEN', 'AF'),
    ('Kyrgyzstan', 'KG', 'KGZ', 'AS'),
    ('Cambodia', 'KH', 'KHM', 'AS'),
    ('Kiribati', 'KI', 'KIR', 'OC'),
    ('Comoros', 'KM', 'COM', 'AF'),
    ('Saint Kitts and Nevis', 'KN', 'KNA', 'NA'),
    ('North Korea', 'KP', 'PRK', 'AS'),
    ('South Korea', 'KR', 'KOR', 'AS'),
    ('Kuwait', 'KW', 'KWT', 'AS'),
    ('Cayman Islands', 'KY', 'CYM', 'NA'),
    ('Kazakhstan', 'KZ', 'KAZ', 'AS'),
    ('Laos', 'LA', 'LAO', 'AS'),
    ('Lebanon', 'LB', 'LBN', 'AS'),
    ('Saint Lucia', 'LC', 'LCA', 'NA'),
    ('Liechtenstein', 'LI', 'LIE', 'EU'),
    ('Sri Lanka', 'LK', 'LKA', 'AS'),
    ('Liberia', 'LR', 'LBR', 'AF'),
    ('Lesotho', 'LS', 'LSO', 'AF'),
    ('Lithuania', 'LT', 'LTU', 'EU'),
    ('Luxembourg', 'LU', 'LUX', 'EU'),
    ('Latvia', 'LV', 'LVA', 'EU'),
    ('Libya', 'LY', 'LBY', 'AF'),
    ('Morocco', 'MA', 'MAR', 'AF'),
    ('Monaco', 'MC', 'MCO', 'EU'),
    ('Moldova', 'MD', 'MDA', 'EU'),
    ('Montenegro', 'ME', 'MNE', 'EU'),
    ('Saint Martin', 'MF', 'MAF', 'NA'),
    ('Madagascar', 'MG', 'MDG', 'AF'),
    ('Marshall Islands', 'MH', 'MHL', 'OC'),
    ('North Macedonia', 'MK', 'MKD', 'EU'),
    ('Mali', 'ML', 'MLI', 'AF'),
    ('Myanmar', 'MM', 'MMR', 'AS'),
    ('Mongolia', 'MN', 'MNG', 'AS'),
    ('Macao', 'MO', 'MAC', 'AS'),
    ('Northern Mariana Islands', 'MP', 'MNP', 'OC'),
    ('Martinique', 'MQ', 'MTQ', 'NA'),
    ('Mauritania', 'MR', 'MRT', 'AF'),
    ('Montserrat', 'MS', 'MSR', 'NA'),
    ('Malta', 'MT', 'MLT', 'EU'),
    ('Mauritius', 'MU', 'MUS', 'AF'),
    ('Maldives', 'MV', 'MDV', 'AS'),
    ('Malawi', 'MW', 'MWI', 'AF'),
    ('Mexico', 'MX', 'MEX', 'NA'),
    ('Malaysia', 'MY', 'MYS', 'AS'),
    ('Mozambique', 'MZ', 'MOZ', 'AF'),
    ('Namibia', 'NA', 'NAM', 'AF'),
    ('New Caledonia', 'NC', 'NCL', 'OC'),
    ('Niger', 'NE', 'NER', 'AF'),
    ('Norfolk Island', 'NF', 'NFK', 'OC'),
    ('Nigeria', 'NG', 'NGA', 'AF'),
    ('Nicaragua', 'NI', 'NIC', 'NA'),
    ('The Netherlands', 'NL', 'NLD', 'EU'),
    ('Norway', 'NO', 'NOR', 'EU'),
    ('Nepal', 'NP', 'NPL', 'AS'),
    ('Nauru', 'NR', 'NRU', 'OC'),
    ('Niue', 'NU', 'NIU', 'OC'),
    ('New Zealand', 'NZ', 'NZL', 'OC'),
    ('Oman', 'OM', 'OMN', 'AS'),
    ('Panama', 'PA', 'PAN', 'NA'),
    ('Peru', 'PE', 'PER', 'SA'),
    ('French Polynesia', 'PF', 'PYF', 'OC'),
    ('Papua New Guinea', 'PG', 'PNG', 'OC'),
    ('Philippines', 'PH', 'PHL', 'AS'),
    ('Pakistan', 'PK', 'PAK', 'AS'),
    ('Poland', 'PL', 'POL', 'EU'),
    ('Saint Pierre and Miquelon', 'PM', 'SPM', 'NA'),
    ('Pitcairn', 'PN', 'PCN', 'OC'),
    ('Puerto Rico', 'PR', 'PRI', 'NA'),
    ('Palestinian Territory', 'PS', 'PSE', 'AS'),
    ('Portugal', 'PT', 'PRT', 'EU'),
    ('Palau', 'PW', 'PLW', 'OC'),
    ('Paraguay', 'PY', 'PRY', 'SA'),
    ('Qatar', 'QA', 'QAT', 'AS'),
    ('Reunion', 'RE', 'REU', 'AF'),
    ('Romania', 'RO', 'ROU', 'EU'),
    ('Serbia', 'RS', 'SRB', 'EU'),
    ('Russia', 'RU', 'RUS', 'EU'),
    ('Rwanda', 'RW', 'RWA', 'AF'),
    ('Saudi Arabia', 'SA', 'SAU', 'AS'),
    ('Solomon Islands', 'SB', 'SLB', 'OC'),
    ('Seychelles', 'SC', 'SYC', 'AF'),
    ('Sudan', 'SD', 'SDN', 'AF'),
    ('Sweden', 'SE', 'SWE', 'EU'),
    ('Singapore', 'SG', 'SGP', 'AS'),
    ('Saint Helena', 'SH', 'SHN', 'AF'),
    ('Slovenia', 'SI', 'SVN', 'EU'),
    ('Svalbard and Jan Mayen', 'SJ', 'SJM', 'EU'),
    ('Slovakia', 'SK', 'SVK', 'EU'),
    ('Sierra Leone', 'SL', 'SLE', 'AF'),
    ('San Marino', 'SM', 'SMR', 'EU'),
    ('Senegal', 'SN', 'SEN', 'AF'),
    ('Somalia', 'SO', 'SOM', 'AF'),
    ('Suriname', 'SR', 'SUR', 'SA'),
    ('South Sudan', 'SS', 'SSD', 'AF'),
    ('Sao Tome and Principe', 'ST', 'STP', 'AF'),
    ('El Salvador', 'SV', 'SLV', 'NA'),
    ('Sint Maarten', 'SX', 'SXM', 'NA'),
    ('Syria', 'SY', 'SYR', 'AS'),
    ('Eswatini', 'SZ', 'SWZ', 'AF'),
    ('Turks and Caicos Islands', 'TC', 'TCA', 'NA'),
    ('Chad', 'TD', 'TCD', 'AF'),
    ('French Southern Territories', 'TF', 'ATF', 'AN'),
    ('Togo', 'TG', 'TGO', 'AF'),
    ('Thailand', 'TH', 'THA', 'AS'),
    ('Tajikistan', 'TJ', 'TJK', 'AS'),
    ('Tokelau', 'TK', 'TKL', 'OC'),
    ('Timor Leste', 'TL', 'TLS', 'OC'),
    ('Turkmenistan', 'TM', 'TKM', 'AS'),
    ('Tunisia', 'TN', 'TUN', 'AF'),
    ('Tonga', 'TO', 'TON', 'OC'),
    ('Turkey', 'TR', 'TUR', 'AS'),
    ('Trinidad and Tobago', 'TT', 'TTO', 'NA'),
    ('Tuvalu', 'TV', 'TUV', 'OC'),
    ('Taiwan', 'TW', 'TWN', 'AS'),
    ('Tanzania', 'TZ', 'TZA', 'AF'),
    ('Ukraine', 'UA', 'UKR', 'EU'),
    ('Uganda', 'UG', 'UGA', 'AF'),
    ('United States Minor Outlying Islands', 'UM', 'UMI', 'OC'),
    ('United States', 'US', 'USA', 'NA'),
    ('Uruguay', 'UY', 'URY', 'SA'),
    ('Uzbekistan', 'UZ', 'UZB', 'AS'),
    ('Vatican', 'VA', 'VAT', 'EU'),
    ('Saint Vincent and the Grenadines', 'VC', 'VCT', 'NA'),
    ('Venezuela', 'VE', 'VEN', 'SA'),
    ('British Virgin Islands', 'VG', 'VGB', 'NA'),
    ('U.S. Virgin Islands', 'VI', 'VIR', 'NA'),
    ('Vietnam', 'VN', 'VNM', 'AS'),
    ('Vanuatu', 'VU', 'VUT', 'OC'),
    ('Wallis and Futuna', 'WF', 'WLF', 'OC'),
    ('Samoa', 'WS', 'WSM', 'OC'),
    ('Kosovo', 'XK', 'XKX', 'EU'),
    ('Yemen', 'YE', 'YEM', 'AS'),
    ('Mayotte', 'YT', 'MYT', 'AF'),
    ('South Africa', 'ZA', 'ZAF', 'AF'),
    ('Zambia', 'ZM', 'ZMB', 'AF'),
    ('Zimbabwe', 'ZW', 'ZWE', 'AF'),
)

US_STATES: dict = {
    'alaska': 'Alaska',
    'AK': 'Alaska',
    'alabama': 'Alabama',
    'AL': 'Alabama',
    'arkansas': 'Arkansas',
    'AR': 'Arkansas',
    'american samoa': 'American Samoa',
    'AS': 'American Samoa',
    'arizona': 'Arizona',
    'AZ': 'Arizona',
    'california': 'California',
    'CA': 'California',
    'colorado': 'Colorado',
    'CO': 'Colorado',
    'connecticut': 'Connecticut',
    'CT': 'Connecticut',
    'delaware': 'Delaware',
    'DE': 'Delaware',
    'florida': 'Florida',
    'FL': 'Florida',
    'georgia': 'Georgia',
    'GA': 'Georgia',
    'guam': 'Guam',
    'GU': 'Guam',
    'hawaii': 'Hawaii',
    'HI': 'Hawaii',
    'iowa': 'Iowa',
    'IA': 'Iowa',
    'idaho': 'Idaho',
    'ID': 'Idaho',
    'illinois': 'Illinois',
    'IL': 'Illinois',
    'indiana': 'Indiana',
    'IN': 'Indiana',
    'kansas': 'Kansas',
    'KS': 'Kansas',
    'kentucky': 'Kentucky',
    'KY': 'Kentucky',
    'louisiana': 'Louisiana',
    'LA': 'Louisiana',
    'massachusetts': 'Massachusetts',
    'MA': 'Massachusetts',
    'maryland': 'Maryland',
    'MD': 'Maryland',
    'maine': 'Maine',
    'ME': 'Maine',
    'michigan': 'Michigan',
    'MI': 'Michigan',
    'minnesota': 'Minnesota',
    'MN': 'Minnesota',
    'missouri': 'Missouri',
    'MO': 'Missouri',
    'northern mariana islands': 'Northern Mariana Islands',
    'MP': 'Northern Mariana Islands',
    'mississippi': 'Mississippi',
    'MS': 'Mississippi',
    'montana': 'Montana',
    'MT': 'Montana',
    'north carolina': 'North Carolina',
    'NC': 'North Carolina',
    'north dakota': 'North Dakota',
    'ND': 'North Dakota',
    'nebraska': 'Nebraska',
    'NE': 'Nebraska',
    'new hampshire': 'New Hampshire',
    'NH': 'New Hampshire',
    'new jersey': 'New Jersey',
    'NJ': 'New Jersey',
    'new mexico': 'New Mexico',
    'NM': 'New Mexico',
    'nevada': 'Nevada',
    'NV': 'Nevada',
    'new york': 'New York',
    'NY': 'New York',
    'ohio': 'Ohio',
    'OH': 'Ohio',
    'oklahoma': 'Oklahoma',
    'OK': 'Oklahoma',
    'oregon': 'Oregon',
    'OR': 'Oregon',
    'pennsylvania': 'Pennsylvania',
    'PA': 'Pennsylvania',
    'puerto rico': 'Puerto Rico',
    'PR': 'Puerto Rico',
    'rhode island': 'Rhode Island',
    'RI': 'Rhode Island',
    'south carolina': 'South Carolina',
    'SC': 'South Carolina',
    'south dakota': 'South Dakota',
    'SD': 'South Dakota',
    'tennessee': 'Tennessee',
    'TN': 'Tennessee',
    'texas': 'Texas',
    'TX': 'Texas',
    'utah': 'Utah',
    'UT': 'Utah',
    'virginia': 'Virginia',
    'VA': 'Virginia',
    'virgin islands': 'Virgin Islands',
    'VI': 'Virgin Islands',
    'vermont': 'Vermont',
    'VT': 'Vermont',
    'washington': 'Washington',
    'WA': 'Washington',
    'wisconsin': 'Wisconsin',
    'WI': 'Wisconsin',
    'west virginia': 'West Virginia',
    'WV': 'West Virginia',
    'wyoming': 'Wyoming',
    'WY': 'Wyoming',
}
# fmt: on
